title: Jiatong Su
description: >
  GIS • Data Visualization <br>
  Master of Urban Spatial Analytics ’25, University of Pennsylvania <br>
  Bachelor of Arts in Geography ’23, University of California, Santa Barbara

logo: "/images/IMG_3083.jpg"




# Google Analytics (GA4)
google_analytics: UA-000000-0  #

# 導覽列（用於首頁與所有頁面）
navbar:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/projects.md"
  - title: "About"
    url: "/about/about.md"
  - title: "Resume"
    url: "/resume/resume.md"
    


# 社交連結
social_links:
  linkedin: https://www.linkedin.com/in/jiatong-su-415b71216
  github: https://github.com/sujiatong
